audit_log_path: /var/log/audit/kube-apiserver-audit.log
audit_log_maxage: 30
audit_log_maxbackups: 1
audit_log_maxsize: 100
audit_policy_file: "{{ kube_config_dir }}/audit-policy/apiserver-audit-policy.yaml"
audit_policy_custom_rules: | 
    - level: None
      userGroups:
      - system:serviceaccounts:kube-system
    - level: None
      users:
      - system:apiserver
      - system:kube-controller-manager
      - system:kube-proxy
      - system:kube-scheduler
      - system:node
      - system:volume-scheduler
    # Don't log nodes communications
    - level: None
      userGroups:
      - system:nodes
    # Don't log these read-only URLs.
    - level: None
      nonResourceURLs:
      - /healthz*
      - /version
      - /swagger*
      - /readyz
      - /livez
    # Log all requests at the Metadata level. Omit useless stages
    - level: Metadata
      omitStages:
        - "RequestReceived"
  
  
