NUM_WORKER_NODES=2
IP_NW="10.0.1."
IP_START=10
POD_CIDR="192.168.0.0/16"
KUBERNETES_VERSION="1.24.4-00"
CRIO_VERSION="1.24"
UBUNTU_VERSION="20.04"

Vagrant.configure("2") do |config|
  config.vm.provision "shell", env: {"IP_NW" => IP_NW, "IP_START" => IP_START}, inline: <<-SHELL
      apt-get update -y
      echo "$IP_NW$((IP_START)) master-node" >> /etc/hosts
      echo "$IP_NW$((IP_START+1)) worker-node01" >> /etc/hosts
      echo "$IP_NW$((IP_START+2)) worker-node02" >> /etc/hosts
  SHELL

  config.vm.box = "bento/ubuntu-" + "#{UBUNTU_VERSION}"
  config.vm.box_check_update = true

  config.vm.define "master" do |master|
    # master.vm.box = "bento/ubuntu-18.04"
    master.vm.hostname = "master-node"
    master.vm.network "private_network", ip: IP_NW + "#{IP_START}"
    master.vm.provider "virtualbox" do |vb|
        vb.memory = 4048
        vb.cpus = 2
    end
    master.vm.provision "shell", path: "scripts/common.sh", env: {"KUBERNETES_VERSION" => "#{KUBERNETES_VERSION}", "CRIO_VERSION" => "#{CRIO_VERSION}", "UBUNTU_VERSION" => "#{UBUNTU_VERSION}"}
    master.vm.provision "shell", path: "scripts/master.sh", env: {"MASTER_IP" => IP_NW + "#{IP_START}", "POD_CIDR" => "#{POD_CIDR}"}
  end

  (1..NUM_WORKER_NODES).each do |i|

  config.vm.define "node0#{i}" do |node|
    node.vm.hostname = "worker-node0#{i}"
    node.vm.network "private_network", ip: IP_NW + "#{IP_START + i}"
    node.vm.provider "virtualbox" do |vb|
        vb.memory = 2048
        vb.cpus = 1
    end
    node.vm.provision "shell", path: "scripts/common.sh", env: {"KUBERNETES_VERSION" => "#{KUBERNETES_VERSION}", "CRIO_VERSION" => "#{CRIO_VERSION}", "UBUNTU_VERSION" => "#{UBUNTU_VERSION}"}
    node.vm.provision "shell", path: "scripts/node.sh"
  end

  end
end 