NUM_WORKER_NODES=2
IP_NW="10.0.1."
IP_START=10
UBUNTU_VERSION="20.04"

Vagrant.configure("2") do |config|
  config.vm.provision "shell", env: {"IP_NW" => IP_NW, "IP_START" => IP_START}, inline: <<-SHELL
      apt-get update -y
      echo "$IP_NW$((IP_START+1)) master1" >> /etc/hosts
      echo "$IP_NW$((IP_START+2)) master2" >> /etc/hosts
      echo "$IP_NW$((IP_START+3)) master3" >> /etc/hosts
      echo "$IP_NW$((IP_START+4)) node1" >> /etc/hosts
      echo "$IP_NW$((IP_START+5)) node2" >> /etc/hosts
  SHELL

  config.vm.box = "bento/ubuntu-" + "#{UBUNTU_VERSION}"
  config.vm.box_check_update = true
  config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/id_rsa.pub"
  config.vm.provision "shell", inline: <<-SHELL
    cat /home/vagrant/.ssh/id_rsa.pub >> /home/vagrant/.ssh/authorized_keys
  SHELL
  (1..3).each do |i|
  config.vm.define "master#{i}" do |master|
    master.vm.hostname = "master#{i}"
    master.vm.network "private_network", ip: IP_NW + "#{IP_START + i}"
    master.vm.provider "virtualbox" do |vb|
        vb.memory = 4048
        vb.cpus = 2
    end
  end
  end
  IP_NODE_START = IP_START + 3
  (1..NUM_WORKER_NODES).each do |i|
  
  config.vm.define "node#{i}" do |node|
    node.vm.hostname = "node#{i}"
    node.vm.network "private_network", ip: IP_NW + "#{IP_NODE_START + i}"
    node.vm.provider "virtualbox" do |vb|
        vb.memory = 2048
        vb.cpus = 1
    end
  end

  end
end 